<a href="https://colab.research.google.com/github/AdriannMo/E50A-E01/blob/main/Miner%C3%ADa_de_Datos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Minería de Datos

## Primer parcial

### Introducción

#### Conceptos

#### Ciencia de Datos

Help and Documentation in IPython

In [ ]:
# La funcion help nos muestra la ayuda
help(len)

Help on built-in function len in module builtins:

len(obj, /)
    Return the number of items in a container.



In [ ]:
# Otra forma de obtener ayuda es utilizando ?
len?

In [ ]:
# Ejemplo de ayuda en una lista
L = [1, 2, 3]
L.insert?

In [ ]:
# Otro ejemplo de ayuda
L?

In [ ]:
# Ejemplo con una función con Docstring
def square(a):
    """Return the square of a."""
    return a ** 2

In [ ]:
help(square)

Help on function square in module __main__:

square(a)
    Return the square of a.



In [ ]:
# Ejemplo de ayuda de funcion personalizada
square??

In [ ]:
len??

In [ ]:
L.insert

In [ ]:
from itertools import combinations

IPython Magic Commands

In [ ]:
# El comado mágico %timeit sirve para evaluar el
# desempeño, en términos de tiempo
%timeit L = [n ** 2 for n in range(1000)]

39.8 µs ± 1.5 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [ ]:
# El comando mágico %%timeit sirve también para evaluar el desempeño
# solo que este abarca varias líneas de código en lugar de una
%%timeit
L = []
for n in range(1000):
    L.append(n ** 2)

44.5 µs ± 743 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [ ]:
%timeit?

In [ ]:
%%timeit?

IPython and Shell Commands

In [ ]:
!ls

sample_data


In [ ]:
%cd sample_data/

/content/sample_data


In [ ]:
%ls

anscombe.json*                mnist_test.csv
california_housing_test.csv   mnist_train_small.csv
california_housing_train.csv  README.md*


In [ ]:
%env

{'SHELL': '/bin/bash',
 'COLAB_JUPYTER_TRANSPORT': 'ipc',
 'CGROUP_MEMORY_EVENTS': '/sys/fs/cgroup/memory.events /var/colab/cgroup/jupyter-children/memory.events',
 'VM_GCE_METADATA_HOST': '169.254.169.253',
 'MODEL_PROXY_HOST': 'https://mp.kaggle.net',
 'HOSTNAME': 'f0713b3fa0c6',
 'LANGUAGE': 'en_US',
 'TBE_RUNTIME_ADDR': '172.28.0.1:8011',
 'GCE_METADATA_TIMEOUT': '3',
 'COLAB_JUPYTER_IP': '172.28.0.12',
 'COLAB_LANGUAGE_SERVER_PROXY_ROOT_URL': 'http://172.28.0.1:8013/',
 'KMP_LISTEN_PORT': '6000',
 'TF_FORCE_GPU_ALLOW_GROWTH': 'true',
 'ENV': '/root/.bashrc',
 'PWD': '/',
 'COLAB_LANGUAGE_SERVER_PROXY_REQUEST_TIMEOUT': '30s',
 'TBE_EPHEM_CREDS_ADDR': '172.28.0.1:8009',
 'TBE_CREDS_ADDR': '172.28.0.1:8008',
 'COLAB_JUPYTER_TOKEN': '<hidden>',
 'LAST_FORCED_REBUILD': '20250623',
 'TCLLIBPATH': '/usr/share/tcltk/tcllib1.20',
 'COLAB_KERNEL_MANAGER_PROXY_HOST': '172.28.0.12',
 'UV_BUILD_CONSTRAINT': '',
 'COLAB_WARMUP_DEFAULTS': '1',
 'HOME': '/root',
 'LANG': 'en_US.UTF-8',
 'CLOUDSDK

Understanding Data Types in Python

In [ ]:
import numpy as np

In [ ]:
np.array([1, 4, 2, 5, 3])

array([1, 4, 2, 5, 3])

In [ ]:
np.array([3.14, 4, 2, 3])

array([3.14, 4.  , 2.  , 3.  ])

In [ ]:
np.array([1, 2, 3, 4], dtype='float32')

array([1., 2., 3., 4.], dtype=float32)

In [ ]:
np.array([1, 2, 3, 4], dtype='int')

array([1, 2, 3, 4])

In [ ]:
# Cuando el argumento de np.array es una iteración anidada genera una matriz
np.array([range(i, i + 3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [ ]:
[range(i, i + 3) for i in [2, 4, 6]]

[range(2, 5), range(4, 7), range(6, 9)]

In [ ]:
import array
L = list(range(10))
A = array.array('i', L)

In [ ]:
print(A)

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


In [ ]:
import numpy as np

In [ ]:
# integer array:
np.array([1, 4, 2, 5, 3])

array([1, 4, 2, 5, 3])

In [ ]:
np.array([3.14, 4, 2, 3])

array([3.14, 4.  , 2.  , 3.  ])

In [ ]:
np.array([1, 2, 3, 4], dtype='float32')

array([1., 2., 3., 4.], dtype=float32)

In [ ]:
np.array([range(i, i + 3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [ ]:
# Crear un array entero de longitud 10 relleno de ceros
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
# Crea un array de punto flotante 3x5 lleno de unos
np.ones((3, 5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
# Crear un array 3x5 lleno de 3.14
np.full((3, 5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [ ]:
# Crear un array relleno de una secuencia lineal
# Empezando en 0, terminando en 20, subiendo en 2
# (esto es similar a la función de rango() incorporada)
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
# Crear un array de cinco valores espaciados uniformemente entre 0 y 1
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [ ]:
# Crear un array 3x3 de distribución uniforme
# random values between 0 and 1
np.random.random((3, 3))

array([[0.44112214, 0.17171926, 0.76670632],
       [0.16162459, 0.05484375, 0.3139478 ],
       [0.9159399 , 0.17781616, 0.03190489]])

In [ ]:
# Crear un array 3x3 de valores aleatorios distribuidos normalmente
# con media 0 y desviación estándar 1
np.random.normal(0, 1, (3, 3))

array([[ 1.12535011,  0.44189058, -0.76754003],
       [ 0.20447387,  0.23530933,  0.29858643],
       [ 1.63492976,  0.82882981, -1.91488636]])

In [ ]:
# Crear un array 3x3 de enteros aleatorios en el intervalo [0, 10)
np.random.randint(0, 10, (3, 3))

array([[4, 5, 2],
       [7, 2, 7],
       [0, 0, 8]])

In [ ]:
# Crear una matriz identidad 3x3
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

####The basics of Numpy Arrays

In [ ]:
np.random.seed(0) # semilla para la reproducibilidad
x1 = np.random.randint(10, size=6)  # One-dimensional array
x2 = np.random.randint(10, size=(3, 4))  # Two-dimensional array
x3 = np.random.randint(10, size=(3, 4, 5))  # Three-dimensional array

In [ ]:
print("x3 ndim: ", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size: ", x3.size)

x3 ndim:  3
x3 shape: (3, 4, 5)
x3 size:  60


In [ ]:
print("dtype:", x3.dtype)

dtype: int64


In [ ]:
print("itemsize:", x3.itemsize, "bytes")
print("nbytes:", x3.nbytes, "bytes")

itemsize: 8 bytes
nbytes: 480 bytes


In [ ]:
x1

array([5, 0, 3, 3, 7, 9])

In [ ]:
#Traer el primer elemento
x1[0]

np.int64(5)

In [ ]:
x1[4]

np.int64(7)

In [ ]:
x1[-1]

np.int64(9)

In [ ]:
x1[-2]

np.int64(7)

In [ ]:
x1[-6]

np.int64(5)

In [ ]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [ ]:
x2[0, 2]

np.int64(2)

In [ ]:
x2[2, 1]

np.int64(6)

In [ ]:
x2[-1, -1] =12
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7, 12]])

In [ ]:
x1[0] = 3.14159  # this will be truncated!
x1

array([3, 0, 3, 3, 7, 9])

####Análisis Estadístico Básico con Numpy

Media (Mean)

In [42]:
data = np.array([1, 2, 3, 4, 5])
media = np.mean(data)
print(media)

3.0


Promedio (Average) y Promedio Ponderado

In [44]:
data = np.array([1, 2, 3, 4, 5])
weights = np.array([1, 2, 3, 4, 5])
promedio = np.average(data)
promedio_ponderado = np.average(data, weights=weights)

In [45]:
print(promedio)
print(promedio_ponderado)

3.0
3.6666666666666665


Mediana

In [46]:
mediana = np.median(data)

Varianza y Desviación Estándar

In [47]:
varianza = np.var(data)
desviacion = np.std(data)

In [50]:
print(varianza)
print(desviacion)

2.0
1.4142135623730951


Generación de Datos Aleatorios

In [48]:
muestra = np.random.normal(0, 1, 1000) #Mil datos con una media de 0 y una desviación estándar de 1
print(np.mean(muestra), np.std(muestra))

-0.006543456960417206 1.0059985778093545


Correlación

In [51]:
corr = np.corrcoef([1,2,3], [1,5,7]) #Comparando 2 listas
print(corr)  #Si es cercano a 1 se dice que si hay relación

[[1.         0.98198051]
 [0.98198051 1.        ]]


Funciones Estadísticas Adicionales (NumPy)

Cuantiles (np.quantile)

Percentiles (np.percentile)

Histogramas (np.histogram)

Covarianza (np.cov)

Manejo de NaN (np.nanmean, etc.)

Conclusión

NumPy facilita el análisis estadístico al proporcionar funciones optimizadas para cálculos comunes como media, mediana, varianza, desviación estándar y correlación. Además, ofrece herramientas para generar datos y analizar distribuciones.